// Run with: node scripts/bake-icons.js
// Fetches all unique MDI icons used in ICON_MAP and writes them as inline SVG
// strings to src/icons/bakedIcons.ts so no runtime network requests are needed.

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

// Extract unique mdi:* icon names from iconList.ts via regex
const iconListSrc = readFileSync(join(root, 'src/icons/iconList.ts'), 'utf8')
const iconNames = [...new Set(
  [...iconListSrc.matchAll(/'(mdi:[^']+)'/g)].map(m => m[1])
)]

console.log(`Fetching ${iconNames.length} unique icons...`)

const baked = {}

for (const iconName of iconNames) {
  const [, name] = iconName.split(':')
  const url = `https://api.iconify.design/mdi/${name}.svg`
  try {
    const res = await fetch(url)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const svg = await res.text()
    baked[iconName] = svg.trim()
    process.stdout.write('.')
  } catch (e) {
    console.error(`\nFailed: ${iconName} — ${e.message}`)
  }
}

const entries = Object.entries(baked)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
  .join(',\n')

const output = `// AUTO-GENERATED by scripts/bake-icons.js — do not edit manually
// Re-run "npm run bake-icons" to refresh after changing iconList.ts
export const BAKED_ICONS: Record<string, string> = {
${entries}
}
`

writeFileSync(join(root, 'src/icons/bakedIcons.ts'), output)
console.log(`\nWrote ${Object.keys(baked).length} icons to src/icons/bakedIcons.ts`)
